{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) .Values.postgresql.auth.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "titiler.postgresql.fullname" . }}
  labels:
    {{- include "titiler.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
