{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "titiler.postgresql.fullname" . }}
  labels:
    {{- include "titiler.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "titiler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
