{{- if .Values.cloudferro.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "titiler.fullname" . }}-cloudferro-credentials
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: credentials-fetcher
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          CREDS=$(curl -s http://169.254.169.254/openstack/latest/vendor_data2.json)
          ACCESS_KEY=$(echo $CREDS | jq -r '.nova.vmconfig.mountpoints[0].s3_access_key')
          SECRET_KEY=$(echo $CREDS | jq -r '.nova.vmconfig.mountpoints[0].s3_secret_key')
          S3_URL=$(echo $CREDS | jq -r '.nova.vmconfig.mountpoints[0].s3_url')
          
          kubectl create secret generic {{ include "titiler.fullname" . }}-cloudferro-credentials \
            --from-literal=AWS_ACCESS_KEY_ID=$ACCESS_KEY \
            --from-literal=AWS_SECRET_ACCESS_KEY=$SECRET_KEY \
            --from-literal=AWS_S3_ENDPOINT=$S3_URL \
            -o yaml --dry-run=client | kubectl apply -f -
      restartPolicy: Never
      serviceAccountName: {{ include "titiler.fullname" . }}-cloudferro
{{- end }}
