apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "titiler.fullname" . }}-configmap
data:
  {{- if .Values.netrc }}
  netrc: {{ tpl (.Values.netrc) . | quote }}
  {{- end }}
  log_config.yaml: |-
    {{ .Files.Get .Values.logging.configFile | nindent 4 }}
  {{- if .Values.persistence.localStoreSeed }}
  init_store.json: |-
    {{ .Files.Get .Values.persistence.localStoreSeed | nindent 4 }}
  {{- end }}
