apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "titiler.fullname" . }}-configmap
data:
  {{- if .Values.netrc }}
  netrc: {{ tpl (.Values.netrc) . | quote }}
  {{- end }}
  {{- if .Values.service.store }}
  local_store.json: |-
    {{ .Files.Get .Values.service.store | nindent 4 }}
  {{- end }}
