apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "titiler.fullname" . }}-init
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: init
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          if [ -f "/config/init_store.json" ]; then
            echo "Initializing local_store.json from init_store.json..."
            cp /config/init_store.json /data/local_store.json
            echo "Initialization complete."
          else
            echo "No init_store.json found in configmap, skipping initialization."
          fi
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "titiler.fullname" . }}-pvc
      - name: config
        configMap:
          name: {{ include "titiler.fullname" . }}-configmap
