{{- if and (or (eq .Values.database.type "json") (eq .Values.database.type "duckdb")) .Values.database.persistence.enabled (not .Values.database.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "titiler.fullname" . }}-data
  labels:
    {{- include "titiler.labels" . | nindent 4 }}
  {{- with .Values.database.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.database.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size | quote }}
  {{- if .Values.database.persistence.storageClassName }}
  storageClassName: {{ .Values.database.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
